# Generated by Django 5.0.14 on 2026-05-06 03:07

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_organization_plan_expires_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_inventory_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_categories",
                        to="accounts.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_categories",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Category",
                "verbose_name_plural": "Inventory Categories",
                "db_table": "inv_category",
                "ordering": ["name"],
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("contact_name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("tax_id", models.CharField(blank=True, max_length=50)),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("cod", "Cash on Delivery"),
                            ("net7", "Net 7"),
                            ("net15", "Net 15"),
                            ("net30", "Net 30"),
                            ("net60", "Net 60"),
                        ],
                        default="cod",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_suppliers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suppliers",
                        to="accounts.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "inv_supplier",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sku", models.CharField(blank=True, max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilogram"),
                            ("g", "Gram"),
                            ("liter", "Liter"),
                            ("ml", "Milliliter"),
                            ("piece", "Piece"),
                            ("box", "Box"),
                            ("bag", "Bag"),
                            ("dozen", "Dozen"),
                            ("pack", "Pack"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "reorder_level",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "reorder_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "current_stock",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Computed by signal from StockMovement ledger. Do not write directly.",
                        max_digits=12,
                    ),
                ),
                (
                    "tolerance_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.5"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("5")),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_perishable", models.BooleanField(default=False)),
                ("expiry_days", models.PositiveIntegerField(blank=True, null=True)),
                ("barcode", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="inventory.inventorycategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_inventory_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_items",
                        to="accounts.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="accounts.organization",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "inv_item",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.UUIDField()),
                ("object_repr", models.CharField(max_length=200)),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("diff", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_audit_logs",
                        to="accounts.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_audit_logs",
                        to="accounts.organization",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "inv_audit_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["organization", "-timestamp"],
                        name="inv_audit_l_organiz_d31730_idx",
                    ),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="inv_audit_l_model_n_bf694d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("low_stock", "Low Stock"),
                            ("expiry", "Expiring Soon"),
                            ("negative_stock", "Negative Stock"),
                            ("variance", "Variance Detected"),
                            ("overstock", "Overstock"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("whatsapp_sent", models.BooleanField(default=False)),
                ("whatsapp_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_alerts",
                        to="accounts.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_alerts",
                        to="accounts.organization",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_inventory_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "inv_stock_alert",
                "ordering": ["-triggered_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "is_resolved"],
                        name="inv_stock_a_organiz_75525d_idx",
                    ),
                    models.Index(
                        fields=["item", "is_resolved"],
                        name="inv_stock_a_item_id_d93636_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("sale", "Sale"),
                            ("waste", "Waste / Spoilage"),
                            ("adjustment", "Manual Adjustment"),
                            ("recipe_consumption", "Recipe Consumption"),
                            ("supplier_return", "Supplier Return"),
                            ("opening_stock", "Opening Stock"),
                            ("import_sale", "Imported Sale"),
                            ("import_purchase", "Imported Purchase"),
                        ],
                        max_length=24,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("reference_id", models.CharField(blank=True, max_length=200)),
                ("reference_type", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("movement_date", models.DateField(default=datetime.date.today)),
                ("batch_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("is_reversed", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="accounts.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="accounts.organization",
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversal_of",
                        to="inventory.stockmovement",
                    ),
                ),
            ],
            options={
                "db_table": "inv_stock_movement",
                "ordering": ["-movement_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["item", "movement_date"],
                        name="inv_stock_m_item_id_532854_idx",
                    ),
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="inv_stock_m_organiz_355dd2_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["organization", "is_active"],
                name="inv_supplie_organiz_12e7a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["organization", "is_active"], name="inv_item_organiz_2ee32e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["organization", "category"], name="inv_item_organiz_eb10e2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventoryitem",
            unique_together={("organization", "barcode"), ("organization", "sku")},
        ),
    ]
