# Generated by Django 4.2.30 on 2026-05-07 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_organization_plan_expires_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0003_locationstock"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationItemPricing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "inv_location_item_pricing",
                "ordering": ["item__name"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("to_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=300)),
                ("body", models.TextField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
            ],
            options={
                "db_table": "inv_po_email",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockTake",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("committed", "Committed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="in_progress",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "inv_stock_take",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="StockTakeLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("system_count", models.DecimalField(decimal_places=4, max_digits=12)),
                ("counted", models.DecimalField(decimal_places=4, max_digits=12)),
                ("notes", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "inv_stock_take_line",
                "ordering": ["created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="locationstock",
            new_name="inv_locatio_item_id_b370dc_idx",
            old_name="inv_locatio_item_id_loc_idx",
        ),
        migrations.AddField(
            model_name="stocktakeline",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_take_lines",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="stocktakeline",
            name="stock_take",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="inventory.stocktake",
            ),
        ),
        migrations.AddField(
            model_name="stocktake",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_stock_takes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stocktake",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_takes",
                to="accounts.location",
            ),
        ),
        migrations.AddField(
            model_name="stocktake",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_takes",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderemail",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="inventory.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderemail",
            name="sent_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_po_emails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="locationitempricing",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_pricing",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="locationitempricing",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_pricing",
                to="accounts.location",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stocktakeline",
            unique_together={("stock_take", "item")},
        ),
        migrations.AddIndex(
            model_name="stocktake",
            index=models.Index(
                fields=["organization", "status"], name="inv_stock_t_organiz_48da0b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="locationitempricing",
            unique_together={("item", "location")},
        ),
    ]
