# Generated by Django 4.2.30 on 2026-05-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_locationitempricing_purchaseorderemail_stocktake_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="sent_to_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
