# Generated by Django 4.2.30 on 2026-05-08 09:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_organization_plan_expires_at"),
        ("restaurant", "0001_initial"),
        ("inventory", "0005_purchaseorder_sent_at_purchaseorder_sent_to_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryAIProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("profile", models.JSONField(blank=True, default=dict)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_ai_profile",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "inv_ai_profile",
            },
        ),
        migrations.CreateModel(
            name="RecipeBookingLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batches",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_links",
                        to="restaurant.booking",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_booking_links",
                        to="accounts.organization",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_links",
                        to="inventory.recipe",
                    ),
                ),
            ],
            options={
                "db_table": "inv_recipe_booking_link",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "consumed_at"],
                        name="inv_recipe__organiz_3976a5_idx",
                    )
                ],
                "unique_together": {("booking", "recipe")},
            },
        ),
    ]
