# Generated by Django 4.2.30 on 2026-06-02 01:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_organization_plan_expires_at"),
        ("restaurant", "0002_menupromorule_menuitem_alcohol_brand_and_more"),
        ("inventory", "0006_inventoryaiprofile_recipebookinglink"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumptionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consumption_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("booking_auto", "Booking Auto-consume"),
                            ("promo_sale", "Promo Sale"),
                            ("sales_import", "Sales Import"),
                            ("cocktail_serve", "Cocktail Serve"),
                            ("staff_use", "Staff Use"),
                            ("spoilage", "Spoilage"),
                            ("wastage", "Wastage"),
                            ("complimentary", "Complimentary"),
                            ("giveaway", "Giveaway"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "quantity_consumed",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
            ],
            options={
                "db_table": "inv_consumption_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="formula_type",
            field=models.CharField(
                choices=[
                    ("food_recipe", "Food Recipe"),
                    ("drink_formula", "Drink Formula"),
                    ("cocktail_formula", "Cocktail Formula"),
                    ("batch_recipe", "Batch Recipe"),
                    ("promo_combo_formula", "Promo Combo Formula"),
                ],
                default="food_recipe",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="linked_promo_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_recipes",
                to="restaurant.menupromorule",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="pour_variance_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Overrides per-item tolerance for drink/cocktail formulas. Defaults to INVENTORY_SETTINGS[DEFAULT_POUR_VARIANCE_PERCENT].",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="serving_ml",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total expected serve volume (ml) — drives pour variance.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", "Kilogram"),
                    ("g", "Gram"),
                    ("liter", "Liter"),
                    ("ml", "Milliliter"),
                    ("cl", "Centiliter"),
                    ("fl_oz", "Fluid Ounce"),
                    ("piece", "Piece"),
                    ("box", "Box"),
                    ("bag", "Bag"),
                    ("dozen", "Dozen"),
                    ("pack", "Pack"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["organization", "formula_type"],
                name="inv_recipe_organiz_90fa8c_idx",
            ),
        ),
        migrations.AddField(
            model_name="consumptionlog",
            name="movement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consumption_logs",
                to="inventory.stockmovement",
            ),
        ),
        migrations.AddField(
            model_name="consumptionlog",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consumption_logs",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="consumptionlog",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consumption_logs",
                to="inventory.recipe",
            ),
        ),
        migrations.AddIndex(
            model_name="consumptionlog",
            index=models.Index(
                fields=["organization", "consumption_type", "-created_at"],
                name="inv_consump_organiz_5e2f77_idx",
            ),
        ),
    ]
