# Generated by Django 4.2.27 on 2025-12-27 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="conversation",
            new_name="conversatio_organiz_0461ff_idx",
            old_name="conversatio_organiz_0a6be4_idx",
        ),
        migrations.RenameIndex(
            model_name="conversation",
            new_name="conversatio_channel_2a6efb_idx",
            old_name="conversatio_channel_8e4a5e_idx",
        ),
        migrations.RenameIndex(
            model_name="conversation",
            new_name="conversatio_last_me_99c95c_idx",
            old_name="conversatio_last_ms_9f2c1a_idx",
        ),
        migrations.RenameIndex(
            model_name="message",
            new_name="messages_convers_3ebb41_idx",
            old_name="messages_convers_e95a22_idx",
        ),
        migrations.RenameIndex(
            model_name="message",
            new_name="messages_channel_9cfdfd_idx",
            old_name="messages_channel_f8d3a1_idx",
        ),
    ]
