# Generated by Django 4.2.30 on 2026-06-02 02:19

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0003_organization_plan_expires_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentUseCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("use_case_key", models.SlugField(max_length=64, unique=True)),
                ("display_name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        default="image", help_text="lucide icon name", max_length=64
                    ),
                ),
                ("required_fields", models.JSONField(blank=True, default=list)),
                ("optional_fields", models.JSONField(blank=True, default=list)),
                (
                    "supported_formats",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Allowed aspects, e.g. ["square", "portrait", "landscape"].',
                    ),
                ),
                ("credit_cost", models.PositiveIntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "studio_use_cases",
                "ordering": ["sort_order", "display_name"],
                "indexes": [
                    models.Index(
                        fields=["active", "sort_order"],
                        name="studio_use__active_f508db_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContentPromptTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prompt_template",
                    models.TextField(help_text="Uses {{field_key}} placeholders."),
                ),
                ("negative_prompt", models.TextField(blank=True)),
                ("system_instructions", models.TextField(blank=True)),
                ("provider", models.CharField(blank=True, max_length=64)),
                ("model", models.CharField(blank=True, max_length=64)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "use_case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_template",
                        to="content_studio.contentusecase",
                    ),
                ),
            ],
            options={
                "db_table": "studio_prompt_templates",
            },
        ),
        migrations.CreateModel(
            name="ContentGenerationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("brand_kit_snapshot", models.JSONField(blank=True, default=dict)),
                ("input_payload", models.JSONField(blank=True, default=dict)),
                ("generated_prompt", models.TextField(blank=True)),
                ("negative_prompt", models.TextField(blank=True)),
                ("provider", models.CharField(blank=True, max_length=64)),
                ("model", models.CharField(blank=True, max_length=64)),
                (
                    "output_resolution",
                    models.CharField(default="1024x1024", max_length=12),
                ),
                (
                    "aspect",
                    models.CharField(
                        choices=[
                            ("square", "Square"),
                            ("portrait", "Portrait"),
                            ("landscape", "Landscape"),
                        ],
                        default="square",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("blocked_by_cap", "Blocked by Spend Cap"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("credits_estimated", models.PositiveIntegerField(default=1)),
                ("credits_used", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cost_estimated_usd",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "cost_actual_usd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("output_count", models.PositiveIntegerField(default=0)),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                ("usage_event_id", models.UUIDField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_jobs",
                        to="accounts.organization",
                    ),
                ),
                (
                    "use_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="content_studio.contentusecase",
                    ),
                ),
            ],
            options={
                "db_table": "studio_generation_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BrandKit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("restaurant_name", models.CharField(blank=True, max_length=200)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, max_length=300, null=True, upload_to="brand_kits/"
                    ),
                ),
                (
                    "brand_colors",
                    models.JSONField(
                        blank=True, default=list, help_text="List of hex colors."
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(default="zh-TW", max_length=10),
                ),
                ("default_cta", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("whatsapp", models.CharField(blank=True, max_length=40)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("website_url", models.URLField(blank=True)),
                ("social_handles", models.JSONField(blank=True, default=dict)),
                (
                    "watermark_preference",
                    models.CharField(
                        choices=[("none", "None"), ("logo", "Logo"), ("text", "Text")],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("style_preferences", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_kit",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "studio_brand_kits",
            },
        ),
        migrations.CreateModel(
            name="ContentGenerationOutput",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ImageField(
                        blank=True,
                        max_length=300,
                        null=True,
                        upload_to="content_studio/",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        max_length=300,
                        null=True,
                        upload_to="content_studio/thumbs/",
                    ),
                ),
                ("file_type", models.CharField(blank=True, max_length=20)),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                ("format", models.CharField(blank=True, max_length=12)),
                ("provider_asset_id", models.CharField(blank=True, max_length=200)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("is_favorite", models.BooleanField(default=False)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outputs",
                        to="content_studio.contentgenerationjob",
                    ),
                ),
            ],
            options={
                "db_table": "studio_generation_outputs",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["job", "created_at"],
                        name="studio_gene_job_id_6562b8_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="contentgenerationjob",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="studio_gene_organiz_88bfb3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentgenerationjob",
            index=models.Index(
                fields=["organization", "status"], name="studio_gene_organiz_cfc271_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentgenerationjob",
            index=models.Index(fields=["status"], name="studio_gene_status_277706_idx"),
        ),
    ]
