# Generated by Django 4.2.30 on 2026-10-04 13:07

import apps.realestate.photo_storage
import apps.showcase.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShowcaseVideo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='Shown above the video, e.g. "Meet the Kribaat agent".',
                        max_length=120,
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="One line under the title.",
                        max_length=240,
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        help_text="MP4 (H.264) recommended, up to 48 MB.",
                        storage=apps.realestate.photo_storage.photo_storage,
                        upload_to=apps.showcase.models._video_path,
                        validators=[apps.showcase.models.validate_video],
                    ),
                ),
                (
                    "poster",
                    models.FileField(
                        blank=True,
                        help_text="Optional cover image shown before playback (16:9).",
                        storage=apps.realestate.photo_storage.photo_storage,
                        upload_to=apps.showcase.models._poster_path,
                        validators=[apps.showcase.models.validate_poster],
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("landing", "kribaat.com landing page"),
                            (
                                "properties",
                                "Property site (kribaat.com/realestate/properties)",
                            ),
                        ],
                        default="landing",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Only active videos are shown publicly."
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Lower shows first."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["placement", "sort_order", "-created_at"],
            },
        ),
    ]
