# Generated by Django 4.2.27 on 2025-12-28 09:31

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "messaging",
            "0002_rename_conversatio_organiz_0a6be4_idx_conversatio_organiz_0461ff_idx_and_more",
        ),
        ("accounts", "0002_alter_location_options_alter_organization_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyListing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "listing_type",
                    models.CharField(
                        choices=[
                            ("sale", "For Sale"),
                            ("rent", "For Rent"),
                            ("lease", "For Lease"),
                        ],
                        default="sale",
                        max_length=20,
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("house", "House"),
                            ("apartment", "Apartment"),
                            ("condo", "Condo"),
                            ("townhouse", "Townhouse"),
                            ("land", "Land"),
                            ("commercial", "Commercial"),
                            ("office", "Office"),
                            ("retail", "Retail"),
                            ("industrial", "Industrial"),
                            ("other", "Other"),
                        ],
                        default="house",
                        max_length=20,
                    ),
                ),
                ("reference_number", models.CharField(max_length=50, unique=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "price_per_sqft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "rent_period",
                    models.CharField(
                        blank=True, help_text="monthly, weekly, yearly", max_length=20
                    ),
                ),
                ("address_line1", models.CharField(max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(default="USA", max_length=100)),
                ("neighborhood", models.CharField(blank=True, max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("bedrooms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "bathrooms",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("square_feet", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "lot_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="Lot size in square feet", null=True
                    ),
                ),
                ("year_built", models.PositiveIntegerField(blank=True, null=True)),
                ("parking_spaces", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of features: pool, garage, garden, etc.",
                    ),
                ),
                (
                    "amenities",
                    models.JSONField(
                        blank=True, default=list, help_text="List of amenities"
                    ),
                ),
                (
                    "images",
                    models.JSONField(
                        blank=True, default=list, help_text="List of image URLs"
                    ),
                ),
                ("virtual_tour_url", models.URLField(blank=True)),
                ("agent_name", models.CharField(blank=True, max_length=255)),
                ("agent_phone", models.CharField(blank=True, max_length=20)),
                ("agent_email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("sold", "Sold"),
                            ("rented", "Rented"),
                            ("off_market", "Off Market"),
                            ("coming_soon", "Coming Soon"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("listed_date", models.DateField(blank=True, null=True)),
                ("sold_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Office/branch handling this listing",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_listings",
                        to="accounts.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_listings",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Listing",
                "verbose_name_plural": "Property Listings",
                "db_table": "realestate_property_listings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("buy", "Buy"),
                            ("rent", "Rent"),
                            ("sell", "Sell"),
                            ("invest", "Invest"),
                            ("general", "General Inquiry"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("unqualified", "Unqualified"),
                            ("converted", "Converted"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("hot", "Hot"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Website Widget"),
                            ("whatsapp", "WhatsApp"),
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("referral", "Referral"),
                            ("walk_in", "Walk-in"),
                            ("other", "Other"),
                        ],
                        default="website",
                        max_length=20,
                    ),
                ),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "preferred_areas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of preferred neighborhoods/areas",
                    ),
                ),
                (
                    "preferred_property_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of preferred property types",
                    ),
                ),
                ("bedrooms_min", models.PositiveIntegerField(blank=True, null=True)),
                ("bedrooms_max", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "timeline",
                    models.CharField(
                        blank=True,
                        help_text='e.g., "Immediately", "1-3 months", "6+ months"',
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "qualification_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="AI-extracted qualification info from conversation",
                    ),
                ),
                (
                    "lead_score",
                    models.PositiveIntegerField(
                        default=0, help_text="Lead quality score 0-100"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contacted_at", models.DateTimeField(blank=True, null=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="messaging.conversation",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Office handling this lead",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="accounts.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="accounts.organization",
                    ),
                ),
                (
                    "property_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="realestate.propertylisting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "db_table": "realestate_leads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("viewing", "Property Viewing"),
                            ("consultation", "Consultation"),
                            ("virtual_tour", "Virtual Tour"),
                            ("meeting", "Meeting"),
                            ("follow_up", "Follow Up"),
                        ],
                        default="viewing",
                        max_length=20,
                    ),
                ),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                (
                    "meeting_location",
                    models.TextField(
                        blank=True,
                        help_text="Meeting location if different from property address",
                    ),
                ),
                ("virtual_meeting_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "outcome",
                    models.TextField(
                        blank=True, help_text="Notes about the appointment outcome"
                    ),
                ),
                ("confirmation_code", models.CharField(max_length=20, unique=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "assigned_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="messaging.conversation",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="realestate.lead",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="accounts.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="accounts.organization",
                    ),
                ),
                (
                    "property_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="realestate.propertylisting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "db_table": "realestate_appointments",
                "ordering": ["appointment_date", "appointment_time"],
            },
        ),
        migrations.AddIndex(
            model_name="propertylisting",
            index=models.Index(
                fields=["organization", "status", "listing_type"],
                name="realestate__organiz_60b7ac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="propertylisting",
            index=models.Index(
                fields=["city", "property_type"], name="realestate__city_bdfe84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertylisting",
            index=models.Index(fields=["price"], name="realestate__price_430e67_idx"),
        ),
        migrations.AddIndex(
            model_name="propertylisting",
            index=models.Index(
                fields=["reference_number"], name="realestate__referen_cd4789_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["organization", "status", "priority"],
                name="realestate__organiz_583810_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["assigned_to", "status"], name="realestate__assigne_1bf061_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["phone"], name="realestate__phone_ed7abc_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["email"], name="realestate__email_6ed2de_idx"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["organization", "appointment_date", "status"],
                name="realestate__organiz_9f169e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["lead", "status"], name="realestate__lead_id_a06585_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["assigned_agent", "appointment_date"],
                name="realestate__assigne_3116f2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["confirmation_code"], name="realestate__confirm_3edde5_idx"
            ),
        ),
    ]
