# Generated by Django 4.2.30 on 2026-10-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("realestate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertylisting",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("house", "House"),
                    ("apartment", "Apartment"),
                    ("room", "Room"),
                    ("condo", "Condo"),
                    ("townhouse", "Townhouse"),
                    ("land", "Land"),
                    ("commercial", "Commercial"),
                    ("office", "Office"),
                    ("retail", "Retail"),
                    ("industrial", "Industrial"),
                    ("other", "Other"),
                ],
                default="house",
                max_length=20,
            ),
        ),
    ]
