# Generated by Django 4.2.30 on 2026-10-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("realestate", "0002_property_type_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="followup_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="propertylisting",
            name="view_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="propertylisting",
            name="whatsapp_clicks",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="propertylisting",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="propertylisting",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
