# Generated by Django 4.2.30 on 2026-10-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("realestate", "0003_listing_public_site_and_appointment_followup"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="attendee_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
