# Generated by Django 4.2.30 on 2026-08-20 17:02

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restaurant", "0002_menupromorule_menuitem_alcohol_brand_and_more"),
        ("crm", "0002_seed_system_tags_existing_orgs"),
        ("accounts", "0003_organization_plan_expires_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoffeeExperience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("okay", "Okay"),
                            ("not_good", "Not good"),
                        ],
                        max_length=10,
                    ),
                ),
                ("comment", models.TextField(blank=True, max_length=1000)),
                (
                    "routine_context",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("work_nearby", "Work nearby"),
                            ("study_nearby", "Study nearby"),
                            ("live_nearby", "Live nearby"),
                            ("occasional", "Occasionally"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("qr", "QR"),
                            ("whatsapp", "WhatsApp"),
                            ("staff", "Staff"),
                        ],
                        default="qr",
                        max_length=10,
                    ),
                ),
                ("offer_shown_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coffee_experiences",
                        to="crm.crmcustomer",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coffee_experiences",
                        to="accounts.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coffee_experiences",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "coffee_pass_experiences",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CoffeePassPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Coffee Pass — 30 days", max_length=200),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "price_hkd",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="hkd", max_length=3)),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("30.00"),
                        help_text="0 < value <= 50. The customer-facing discount on eligible items.",
                        max_digits=5,
                    ),
                ),
                ("duration_days", models.PositiveIntegerField(default=30)),
                ("allow_neutral_feedback", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("break_even_acknowledged", models.BooleanField(default=False)),
                (
                    "public_token",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coffee_pass_plans_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eligible_items",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Required before activation. Must belong to this organization.",
                        related_name="coffee_pass_plans",
                        to="restaurant.menuitem",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coffee_pass_plans",
                        to="accounts.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coffee_pass_plans",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "coffee_pass_plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CoffeePassPurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("plan_snapshot", models.JSONField(default=dict)),
                ("amount_hkd", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="hkd", max_length=3)),
                (
                    "stripe_session_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("stripe_charge_id", models.CharField(blank=True, max_length=255)),
                ("stripe_receipt_url", models.URLField(blank=True)),
                ("activated", models.BooleanField(default=False)),
                (
                    "refunded_amount_hkd",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coffee_pass_purchases",
                        to="crm.crmcustomer",
                    ),
                ),
                (
                    "experience",
                    models.ForeignKey(
                        blank=True,
                        help_text="The experience that made this customer eligible (audit trail).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchases",
                        to="coffee_pass.coffeeexperience",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coffee_pass_purchases",
                        to="accounts.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coffee_pass_purchases",
                        to="accounts.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="coffee_pass.coffeepassplan",
                    ),
                ),
            ],
            options={
                "db_table": "coffee_pass_purchases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CoffeePassOutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=40)),
                ("aggregate_type", models.CharField(max_length=40)),
                (
                    "aggregate_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("idempotency_key", models.CharField(max_length=120, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "available_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coffee_pass_outbox_events",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "coffee_pass_outbox_events",
                "ordering": ["available_at"],
            },
        ),
        migrations.CreateModel(
            name="CoffeePassOTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=30)),
                ("code_hash", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coffee_pass_otps",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "coffee_pass_otps",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CoffeePassAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("plan_created", "Plan created"),
                            ("plan_updated", "Plan updated"),
                            ("plan_activated", "Plan activated"),
                            ("plan_paused", "Plan paused"),
                            ("experience_submitted", "Experience submitted"),
                            ("checkout_started", "Checkout started"),
                            ("pass_activated", "Pass activated"),
                            ("pass_expired", "Pass expired"),
                            ("pass_suspended", "Pass suspended"),
                            ("pass_restored", "Pass restored"),
                            ("pass_cancelled", "Pass cancelled"),
                            ("refund_processed", "Refund processed"),
                            ("token_minted", "Verification token minted"),
                            ("redemption_created", "Redemption created"),
                            ("redemption_voided", "Redemption voided"),
                            ("notification_sent", "Notification sent"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "correlation_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coffee_pass_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "actor_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coffee_pass_audit_events",
                        to="crm.crmcustomer",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coffee_pass_audit_events",
                        to="accounts.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coffee_pass_audit_events",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "coffee_pass_audit_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CoffeePass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending payment"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                ("plan_snapshot", models.JSONField(default=dict)),
                ("starts_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("suspension_reason", models.CharField(blank=True, max_length=255)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coffee_passes",
                        to="crm.crmcustomer",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coffee_passes",
                        to="accounts.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coffee_passes",
                        to="accounts.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="passes",
                        to="coffee_pass.coffeepassplan",
                    ),
                ),
                (
                    "purchase",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coffee_pass",
                        to="coffee_pass.coffeepasspurchase",
                    ),
                ),
            ],
            options={
                "db_table": "coffee_pass_passes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="coffeeexperience",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="experiences",
                to="coffee_pass.coffeepassplan",
            ),
        ),
        migrations.CreateModel(
            name="CoffeePassVerificationToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "fallback_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coffee_pass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_tokens",
                        to="coffee_pass.coffeepass",
                    ),
                ),
                (
                    "consumed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coffee_pass_tokens_consumed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "coffee_pass_verification_tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["coffee_pass", "-created_at"],
                        name="coffee_pass_coffee__264053_idx",
                    ),
                    models.Index(
                        fields=["expires_at", "consumed_at"],
                        name="coffee_pass_expires_2f2c6c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CoffeePassRedemption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "eligible_subtotal_hkd",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "discount_amount_hkd",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "discount_percent_applied",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("pos_receipt_reference", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("redeemed", "Redeemed"), ("voided", "Voided")],
                        db_index=True,
                        default="redeemed",
                        max_length=10,
                    ),
                ),
                (
                    "redeemed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coffee_pass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="coffee_pass.coffeepass",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coffee_pass_redemptions",
                        to="crm.crmcustomer",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coffee_pass_redemptions",
                        to="accounts.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coffee_pass_redemptions",
                        to="accounts.organization",
                    ),
                ),
                (
                    "redeemed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coffee_pass_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coffee_pass_voids",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "coffee_pass_redemptions",
                "ordering": ["-redeemed_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "location", "-redeemed_at"],
                        name="coffee_pass_organiz_fe16bf_idx",
                    ),
                    models.Index(
                        fields=["coffee_pass", "-redeemed_at"],
                        name="coffee_pass_coffee__29b2e4_idx",
                    ),
                    models.Index(
                        fields=["customer", "-redeemed_at"],
                        name="coffee_pass_custome_031aa2_idx",
                    ),
                    models.Index(
                        fields=["organization", "status"],
                        name="coffee_pass_organiz_27c0c2_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="coffeepassredemption",
            constraint=models.CheckConstraint(
                check=models.Q(("eligible_subtotal_hkd__gte", Decimal("0"))),
                name="coffee_pass_redemption_subtotal_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="coffeepasspurchase",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="coffee_pass_organiz_5e8d1a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coffeepasspurchase",
            index=models.Index(
                fields=["customer", "-created_at"],
                name="coffee_pass_custome_514ee1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coffeepasspurchase",
            index=models.Index(fields=["status"], name="coffee_pass_status_e2b747_idx"),
        ),
        migrations.AddConstraint(
            model_name="coffeepasspurchase",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stripe_payment_intent_id", ""), _negated=True),
                fields=("stripe_payment_intent_id",),
                name="uniq_coffee_pass_intent",
            ),
        ),
        migrations.AddConstraint(
            model_name="coffeepasspurchase",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stripe_session_id", ""), _negated=True),
                fields=("stripe_session_id",),
                name="uniq_coffee_pass_session",
            ),
        ),
        migrations.AddIndex(
            model_name="coffeepassplan",
            index=models.Index(
                fields=["organization", "location", "status"],
                name="coffee_pass_organiz_600843_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coffeepassplan",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="coffee_pass_organiz_01a4a1_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="coffeepassplan",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("discount_percent__gt", 0), ("discount_percent__lte", 50)
                ),
                name="coffee_pass_plan_discount_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="coffeepassplan",
            constraint=models.CheckConstraint(
                check=models.Q(("duration_days__gt", 0)),
                name="coffee_pass_plan_duration_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="coffeepassoutboxevent",
            index=models.Index(
                fields=["status", "available_at"], name="coffee_pass_status_1027bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coffeepassoutboxevent",
            index=models.Index(
                fields=["organization", "event_type"],
                name="coffee_pass_organiz_047bd1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coffeepassotp",
            index=models.Index(
                fields=["organization", "phone", "-created_at"],
                name="coffee_pass_organiz_e66951_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coffeepassotp",
            index=models.Index(
                fields=["expires_at"], name="coffee_pass_expires_eb2710_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coffeepassauditevent",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="coffee_pass_organiz_a74e04_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coffeepassauditevent",
            index=models.Index(
                fields=["organization", "action", "-created_at"],
                name="coffee_pass_organiz_ad49d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coffeepassauditevent",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="coffee_pass_entity__58c64c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coffeepass",
            index=models.Index(
                fields=["customer", "location", "status", "expires_at"],
                name="coffee_pass_custome_5a9871_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coffeepass",
            index=models.Index(
                fields=["organization", "location", "status"],
                name="coffee_pass_organiz_6db878_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coffeepass",
            index=models.Index(
                fields=["status", "expires_at"], name="coffee_pass_status_e35211_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="coffeepass",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("customer", "location", "plan"),
                name="uniq_coffee_pass_active_per_customer_location_plan",
            ),
        ),
        migrations.AddIndex(
            model_name="coffeeexperience",
            index=models.Index(
                fields=["customer", "location", "-created_at"],
                name="coffee_pass_custome_f9e90f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coffeeexperience",
            index=models.Index(
                fields=["organization", "location", "sentiment"],
                name="coffee_pass_organiz_cfcfef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coffeeexperience",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="coffee_pass_organiz_971011_idx",
            ),
        ),
    ]
