# Generated by Django 4.2.30 on 2026-08-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffee_pass", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeepassotp",
            name="delivery_detail",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="coffeepassotp",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("no_channel", "No WhatsApp channel configured"),
                    ("failed", "Delivery failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="coffeepassotp",
            index=models.Index(
                fields=["organization", "delivery_status", "-created_at"],
                name="coffee_pass_organiz_15b921_idx",
            ),
        ),
    ]
