# Generated by Django 4.2.30 on 2026-08-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffee_pass", "0002_coffeepassotp_delivery_detail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffeepassotp",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("unverified", "Accepted, delivery not guaranteed (no template)"),
                    ("no_channel", "No WhatsApp channel configured"),
                    ("failed", "Delivery failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
