# Generated by Django 4.2.27 on 2025-12-29 11:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_alter_location_options_alter_organization_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone_number_id", models.CharField(blank=True, max_length=50)),
                ("business_account_id", models.CharField(blank=True, max_length=50)),
                (
                    "access_token",
                    models.TextField(blank=True, help_text="Meta API access token"),
                ),
                (
                    "verify_token",
                    models.CharField(
                        default=uuid.uuid4,
                        help_text="Token for webhook verification",
                        max_length=100,
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(blank=True, help_text="Auto-generated webhook URL"),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_config",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Configuration",
                "db_table": "channel_whatsapp_config",
            },
        ),
        migrations.CreateModel(
            name="InstagramConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("instagram_business_id", models.CharField(blank=True, max_length=50)),
                (
                    "page_id",
                    models.CharField(
                        blank=True, help_text="Linked Facebook page ID", max_length=50
                    ),
                ),
                (
                    "access_token",
                    models.TextField(blank=True, help_text="Instagram Graph API token"),
                ),
                (
                    "verify_token",
                    models.CharField(
                        default=uuid.uuid4,
                        help_text="Token for webhook verification",
                        max_length=100,
                    ),
                ),
                ("webhook_url", models.URLField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instagram_config",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instagram Configuration",
                "db_table": "channel_instagram_config",
            },
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("whatsapp", "WhatsApp"), ("instagram", "Instagram")],
                        max_length=20,
                    ),
                ),
                ("headers", models.JSONField(default=dict)),
                ("body", models.JSONField(default=dict)),
                ("is_processed", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "channel_webhook_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "created_at"],
                        name="channel_web_source_37b840_idx",
                    )
                ],
            },
        ),
    ]
