# Generated by Django 4.2.27 on 2026-01-19 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0002_alter_location_options_alter_organization_options_and_more"),
        ("messaging", "0003_add_language_fields"),
        ("channels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagerNumber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Manager's WhatsApp number with country code (e.g., 919876543210)",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Manager's name for identification", max_length=100
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        default="manager",
                        help_text="Role: manager, owner, supervisor, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "can_update_hours",
                    models.BooleanField(
                        default=True,
                        help_text="Can update business hours/closing status",
                    ),
                ),
                (
                    "can_respond_queries",
                    models.BooleanField(
                        default=True,
                        help_text="Can respond to customer query escalations",
                    ),
                ),
                (
                    "can_view_bookings",
                    models.BooleanField(
                        default=True, help_text="Can view and manage bookings"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager_numbers",
                        to="accounts.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manager_numbers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "channel_manager_numbers",
                "ordering": ["-is_active", "name"],
                "unique_together": {("organization", "phone_number")},
            },
        ),
        migrations.CreateModel(
            name="TemporaryOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "override_type",
                    models.CharField(
                        choices=[
                            ("hours", "Business Hours"),
                            ("availability", "Availability"),
                            ("special_message", "Special Message"),
                            ("menu", "Menu Update"),
                            ("booking", "Booking Status"),
                            ("general", "General Info"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent - Show First"),
                        ],
                        default="high",
                        max_length=20,
                    ),
                ),
                (
                    "original_message",
                    models.TextField(help_text="Original message from manager"),
                ),
                (
                    "processed_content",
                    models.TextField(
                        help_text="AI-processed content for customer responses"
                    ),
                ),
                (
                    "trigger_keywords",
                    models.JSONField(
                        default=list, help_text="Keywords that activate this override"
                    ),
                ),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this override expires and normal knowledge resumes"
                    ),
                ),
                (
                    "auto_expire_on_next_open",
                    models.BooleanField(
                        default=True,
                        help_text="Auto-expire when business opens next (based on opening hours)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overrides",
                        to="channels.managernumber",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_overrides",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "channel_temporary_overrides",
                "ordering": ["-priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "is_active", "expires_at"],
                        name="channel_tem_organiz_97a354_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ManagerQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_query", models.TextField()),
                (
                    "query_summary",
                    models.TextField(help_text="Summarized query sent to manager"),
                ),
                ("whatsapp_message_id", models.CharField(blank=True, max_length=255)),
                ("manager_response", models.TextField(blank=True)),
                ("response_received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for Manager"),
                            ("answered", "Manager Responded"),
                            ("expired", "No Response (Expired)"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "customer_response",
                    models.TextField(
                        blank=True,
                        help_text="Final response sent to customer based on manager's input",
                    ),
                ),
                ("customer_response_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager_queries",
                        to="messaging.conversation",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queries",
                        to="channels.managernumber",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager_queries",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "channel_manager_queries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "status"],
                        name="channel_man_convers_39a22c_idx",
                    ),
                    models.Index(
                        fields=["manager", "status"],
                        name="channel_man_manager_3f1b0a_idx",
                    ),
                ],
            },
        ),
    ]
