# Generated by Django 4.2.27 on 2026-01-25 04:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_location_options_alter_organization_options_and_more"),
        ("channels", "0002_managernumber_temporaryoverride_managerquery"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingManagerAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("close_with_bookings", "Close with active bookings"),
                            ("cancel_all_bookings", "Cancel all bookings"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("original_message", models.TextField()),
                (
                    "context_data",
                    models.JSONField(
                        default=dict, help_text="Booking details, counts, etc."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_actions",
                        to="channels.managernumber",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_manager_actions",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "channel_pending_manager_actions",
                "ordering": ["-created_at"],
            },
        ),
    ]
