# Generated by Django 4.2.30 on 2026-05-05 04:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_organization_plan_expires_at"),
        ("channels", "0003_pendingmanageraction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhooklog",
            name="source",
            field=models.CharField(
                choices=[
                    ("whatsapp", "WhatsApp"),
                    ("instagram", "Instagram"),
                    ("twilio", "Twilio WhatsApp"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TwilioConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account_sid",
                    models.CharField(
                        blank=True, help_text="Twilio Account SID", max_length=64
                    ),
                ),
                (
                    "auth_token",
                    models.TextField(blank=True, help_text="Twilio Auth Token"),
                ),
                (
                    "from_number",
                    models.CharField(
                        blank=True,
                        help_text="Twilio WhatsApp number in E.164, e.g. +14155238886 (sandbox)",
                        max_length=32,
                    ),
                ),
                (
                    "is_sandbox",
                    models.BooleanField(
                        default=True,
                        help_text="Whether using Twilio's WhatsApp Sandbox (vs. an approved sender)",
                    ),
                ),
                (
                    "sandbox_join_code",
                    models.CharField(
                        blank=True,
                        help_text="Sandbox 'join <code>' that customers send to opt-in (sandbox only)",
                        max_length=64,
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(blank=True, help_text="Auto-generated webhook URL"),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="twilio_config",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Twilio WhatsApp Configuration",
                "db_table": "channel_twilio_config",
            },
        ),
    ]
