# Generated by Django 4.2.27 on 2025-12-27 11:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ai_engine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPromptTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("system_prompt", models.TextField()),
                (
                    "business_types",
                    models.JSONField(
                        default=list,
                        help_text="List of business types this template applies to",
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ai_prompt_templates",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="ailog",
            name="context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="ailog",
            name="intent",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="ailog",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="ai_logs_organiz_73b1f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ailog",
            index=models.Index(
                fields=["conversation"], name="ai_logs_convers_6d6cf9_idx"
            ),
        ),
    ]
