# Generated by Django 4.2.30 on 2026-10-03 07:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_organization_plan_expires_at"),
        ("ai_engine", "0002_aiprompttemplate_ailog_context_ailog_intent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentMemory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[("owner", "Owner playbook"), ("customer", "Customer")],
                        max_length=20,
                    ),
                ),
                ("subject_key", models.CharField(max_length=100)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("facts", models.JSONField(blank=True, default=list)),
                ("summary", models.TextField(blank=True)),
                ("summarized_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_memories",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "ai_agent_memories",
            },
        ),
        migrations.AddConstraint(
            model_name="agentmemory",
            constraint=models.UniqueConstraint(
                fields=("organization", "subject_type", "subject_key"),
                name="uniq_agent_memory_subject",
            ),
        ),
    ]
