# Generated by Django 4.2.30 on 2026-10-03 12:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0003_add_language_fields"),
        ("accounts", "0003_organization_plan_expires_at"),
        ("ai_engine", "0003_agentmemory"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bookings_enabled",
                    models.BooleanField(
                        default=True, help_text="Agent may book viewings"
                    ),
                ),
                (
                    "viewings_need_staff_approval",
                    models.BooleanField(
                        default=False,
                        help_text="Bookings are requests until staff confirm them in Appointments",
                    ),
                ),
                ("viewing_start_hour", models.PositiveSmallIntegerField(default=10)),
                (
                    "viewing_end_hour",
                    models.PositiveSmallIntegerField(
                        default=18, help_text="Last slot start hour"
                    ),
                ),
                ("slot_minutes", models.PositiveSmallIntegerField(default=60)),
                ("max_days_ahead", models.PositiveSmallIntegerField(default=60)),
                (
                    "daily_ai_reply_cap",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Max AI replies per day for this org (0 = unlimited)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_settings",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "ai_agent_settings",
            },
        ),
        migrations.CreateModel(
            name="AgentAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("book_viewing", "Book viewing"),
                            ("cancel_appointment", "Cancel appointment"),
                            ("reschedule_appointment", "Reschedule appointment"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("previewed", "Awaiting customer confirmation"),
                            ("executed", "Done"),
                            ("failed", "Failed"),
                            ("superseded", "Replaced by a newer preview"),
                            ("declined", "Customer declined"),
                            ("expired", "Expired"),
                        ],
                        default="previewed",
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("payload_hash", models.CharField(max_length=64)),
                ("receipt", models.JSONField(blank=True, default=dict)),
                ("error", models.CharField(blank=True, max_length=300)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_actions",
                        to="messaging.conversation",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_actions",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "ai_agent_actions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "status", "-created_at"],
                        name="ai_agent_ac_convers_3ce234_idx",
                    )
                ],
            },
        ),
    ]
