# Generated by Django 4.2.30 on 2026-06-03 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0003_organization_plan_expires_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                (
                    "price_hkd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("monthly_image_credits", models.PositiveIntegerField(default=0)),
                (
                    "plan_code",
                    models.CharField(
                        choices=[("basic", "Basic"), ("power", "Power")],
                        default="basic",
                        help_text="Maps to Organization.plan (basic/power).",
                        max_length=20,
                    ),
                ),
                ("enabled_modules", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "billing_subscription_plans",
                "ordering": ["price_hkd"],
            },
        ),
        migrations.CreateModel(
            name="UsageLimit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "monthly_ai_spend_cap_hkd",
                    models.DecimalField(decimal_places=2, default=200, max_digits=10),
                ),
                (
                    "monthly_image_credits_extra_allowed",
                    models.PositiveIntegerField(default=0),
                ),
                ("alert_at_percent", models.PositiveIntegerField(default=80)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_limit",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "billing_usage_limits",
            },
        ),
        migrations.CreateModel(
            name="UsageCreditBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("free_credits_remaining", models.PositiveIntegerField(default=0)),
                ("paid_credits_remaining", models.PositiveIntegerField(default=0)),
                (
                    "free_credits_used_this_month",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "paid_credits_used_this_month",
                    models.PositiveIntegerField(default=0),
                ),
                ("reserved_credits", models.PositiveIntegerField(default=0)),
                (
                    "current_estimated_spend_hkd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cap_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("warning_50", "Warning 50%"),
                            ("warning_80", "Warning 80%"),
                            ("blocked", "Blocked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_balance",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "billing_credit_balances",
            },
        ),
        migrations.CreateModel(
            name="MonthlyUsageSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                ("free_credits_used", models.PositiveIntegerField(default=0)),
                ("paid_credits_used", models.PositiveIntegerField(default=0)),
                (
                    "total_cost_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "total_cost_hkd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "total_billable_hkd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("image_generations", models.PositiveIntegerField(default=0)),
                ("ai_queries", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_summaries",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "billing_monthly_summaries",
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.CreateModel(
            name="AccountSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                            ("trial", "Trial"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("current_period_start", models.DateField()),
                ("current_period_end", models.DateField()),
                (
                    "monthly_ai_spend_cap_hkd",
                    models.DecimalField(decimal_places=2, default=200, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="accounts.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.subscriptionplan",
                    ),
                ),
            ],
            options={
                "db_table": "billing_account_subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UsageEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("content_studio", "Content Studio"),
                            ("inventory_ai", "Inventory AI"),
                            ("chatbot_ai", "Chatbot AI"),
                            ("messaging", "Messaging"),
                        ],
                        max_length=30,
                    ),
                ),
                ("event_type", models.CharField(max_length=60)),
                ("provider", models.CharField(blank=True, max_length=60)),
                ("model", models.CharField(blank=True, max_length=80)),
                ("credits_used", models.PositiveIntegerField(default=0)),
                ("is_free_credit", models.BooleanField(default=False)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "cost_hkd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "billable_amount_hkd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="reserved",
                        max_length=20,
                    ),
                ),
                ("reference_id", models.UUIDField(blank=True, null=True)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("reserved_free", models.PositiveIntegerField(default=0)),
                ("reserved_paid", models.PositiveIntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_events",
                        to="accounts.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = system-initiated.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "billing_usage_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="billing_usa_organiz_508953_idx",
                    ),
                    models.Index(
                        fields=["organization", "module"],
                        name="billing_usa_organiz_a1014f_idx",
                    ),
                    models.Index(
                        fields=["status"], name="billing_usa_status_43e910_idx"
                    ),
                    models.Index(
                        fields=["reference_id"], name="billing_usa_referen_5fc2d5_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="monthlyusagesummary",
            constraint=models.UniqueConstraint(
                fields=("organization", "year", "month"),
                name="uniq_billing_monthly_summary",
            ),
        ),
        migrations.AddIndex(
            model_name="accountsubscription",
            index=models.Index(
                fields=["organization", "status"], name="billing_acc_organiz_ff9a61_idx"
            ),
        ),
    ]
