# Generated by Django 4.2.27 on 2025-12-27 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_location_options_alter_organization_options_and_more"),
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="knowledgebase",
            name="unique_org_location",
        ),
        migrations.AlterUniqueTogether(
            name="knowledgebase",
            unique_together={("organization", "location")},
        ),
    ]
