# Generated by Django 4.2.27 on 2025-12-27 11:23

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["-is_primary", "name"]},
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="organizationmembership",
            options={},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
