# Generated by Django 4.2.27 on 2025-12-28 09:31

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "messaging",
            "0002_rename_conversatio_organiz_0a6be4_idx_conversatio_organiz_0461ff_idx_and_more",
        ),
        ("accounts", "0002_alter_location_options_alter_organization_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, this category is specific to this location only",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_categories",
                        to="accounts.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_categories",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Category",
                "verbose_name_plural": "Menu Categories",
                "db_table": "restaurant_menu_categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DailySpecial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "recurring_days",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Days of week (0=Monday, 6=Sunday). Empty = all days in range.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, this special is for this location only",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_specials",
                        to="accounts.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_specials",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Special",
                "verbose_name_plural": "Daily Specials",
                "db_table": "restaurant_daily_specials",
                "ordering": ["-start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="BookingSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("max_party_size", models.PositiveIntegerField(default=10)),
                (
                    "max_bookings_per_slot",
                    models.PositiveIntegerField(
                        default=5, help_text="Maximum number of bookings per time slot"
                    ),
                ),
                (
                    "total_capacity",
                    models.PositiveIntegerField(
                        default=50, help_text="Total restaurant seating capacity"
                    ),
                ),
                (
                    "slot_duration_minutes",
                    models.PositiveIntegerField(
                        default=30, help_text="Duration of each booking slot in minutes"
                    ),
                ),
                (
                    "booking_buffer_minutes",
                    models.PositiveIntegerField(
                        default=15, help_text="Buffer time between bookings"
                    ),
                ),
                (
                    "min_advance_hours",
                    models.PositiveIntegerField(
                        default=2, help_text="Minimum hours in advance for booking"
                    ),
                ),
                (
                    "max_advance_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Maximum days in advance for booking"
                    ),
                ),
                (
                    "auto_confirm",
                    models.BooleanField(
                        default=True, help_text="Automatically confirm bookings"
                    ),
                ),
                (
                    "cancellation_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="Hours before booking that cancellation is allowed",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_settings",
                        to="accounts.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Settings",
                "verbose_name_plural": "Booking Settings",
                "db_table": "restaurant_booking_settings",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("booking_date", models.DateField()),
                ("booking_time", models.TimeField()),
                (
                    "party_size",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ]
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("customer_phone", models.CharField(max_length=20)),
                ("special_requests", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Website Widget"),
                            ("whatsapp", "WhatsApp"),
                            ("phone", "Phone"),
                            ("walk_in", "Walk-in"),
                            ("other", "Other"),
                        ],
                        default="website",
                        max_length=20,
                    ),
                ),
                ("confirmation_code", models.CharField(max_length=20, unique=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restaurant_bookings",
                        to="messaging.conversation",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurant_bookings",
                        to="accounts.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurant_bookings",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "db_table": "restaurant_bookings",
                "ordering": ["booking_date", "booking_time"],
            },
        ),
        migrations.CreateModel(
            name="OpeningHours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("open_time", models.TimeField(blank=True, null=True)),
                ("close_time", models.TimeField(blank=True, null=True)),
                ("open_time_2", models.TimeField(blank=True, null=True)),
                ("close_time_2", models.TimeField(blank=True, null=True)),
                ("is_closed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_hours",
                        to="accounts.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opening Hours",
                "verbose_name_plural": "Opening Hours",
                "db_table": "restaurant_opening_hours",
                "ordering": ["location", "day_of_week"],
                "unique_together": {("location", "day_of_week")},
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "dietary_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dietary flags: vegetarian, vegan, gluten_free, contains_nuts, etc.",
                    ),
                ),
                (
                    "prep_time_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("image_url", models.URLField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_available", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="restaurant.menucategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Item",
                "verbose_name_plural": "Menu Items",
                "db_table": "restaurant_menu_items",
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active", "is_available"],
                        name="restaurant__categor_c3d85e_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="menucategory",
            index=models.Index(
                fields=["organization", "is_active"],
                name="restaurant__organiz_5ee278_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["organization", "booking_date", "status"],
                name="restaurant__organiz_a5f012_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["location", "booking_date"],
                name="restaurant__locatio_8ecb3a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["confirmation_code"], name="restaurant__confirm_b7b396_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["customer_phone"], name="restaurant__custome_9b5976_idx"
            ),
        ),
    ]
