# Generated by Django 4.2.30 on 2026-06-02 00:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_organization_plan_expires_at"),
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuPromoRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "promo_type",
                    models.CharField(
                        choices=[
                            ("buy_x_get_y", "Buy X Get Y"),
                            ("combo", "Combo"),
                            ("staff_discount", "Staff Discount"),
                            ("happy_hour", "Happy Hour"),
                            ("buffet_session", "Buffet Session"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sales_quantity_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="POS-recorded sold qty per sale.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "revenue_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Revenue per POS unit.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "inventory_deduction_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Inventory units deducted per POS unit (1+1 beer => 2).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("active_from", models.TimeField(blank=True, null=True)),
                ("active_to", models.TimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Menu Promo Rule",
                "verbose_name_plural": "Menu Promo Rules",
                "db_table": "restaurant_promo_rules",
            },
        ),
        migrations.AddField(
            model_name="menuitem",
            name="alcohol_brand",
            field=models.CharField(
                blank=True,
                help_text="Brand for alcohol/cocktail items (e.g. Absolut).",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_alcohol",
            field=models.BooleanField(
                default=False, help_text="Quick alcohol filter without a type join."
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("food", "Food"),
                    ("drink", "Drink"),
                    ("alcohol", "Alcohol"),
                    ("cocktail", "Cocktail"),
                    ("buffet", "Buffet"),
                    ("combo", "Combo"),
                    ("promotion", "Promotion"),
                    ("addon", "Add-on"),
                ],
                default="food",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="sold_out",
            field=models.BooleanField(
                default=False,
                help_text="Transient daily flag — distinct from is_available.",
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["category", "item_type"], name="restaurant__categor_e0c709_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["category", "is_alcohol"], name="restaurant__categor_ed1499_idx"
            ),
        ),
        migrations.AddField(
            model_name="menupromorule",
            name="linked_menu_items",
            field=models.ManyToManyField(
                blank=True,
                help_text="Combo components.",
                related_name="promo_components",
                to="restaurant.menuitem",
            ),
        ),
        migrations.AddField(
            model_name="menupromorule",
            name="menu_item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promo_rule",
                to="restaurant.menuitem",
            ),
        ),
        migrations.AddField(
            model_name="menupromorule",
            name="organization",
            field=models.ForeignKey(
                help_text="Denormalized from menu_item.category.organization (set on save).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_promo_rules",
                to="accounts.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="menupromorule",
            index=models.Index(
                fields=["organization", "promo_type"],
                name="restaurant__organiz_3acb0d_idx",
            ),
        ),
    ]
