# Generated by Django 4.2.30 on 2026-08-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_menupromorule_menuitem_alcohol_brand_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("food", "Food"),
                    ("drink", "Drink"),
                    ("coffee", "Coffee"),
                    ("alcohol", "Alcohol"),
                    ("cocktail", "Cocktail"),
                    ("buffet", "Buffet"),
                    ("combo", "Combo"),
                    ("promotion", "Promotion"),
                    ("addon", "Add-on"),
                ],
                default="food",
                max_length=20,
            ),
        ),
    ]
