# Generated by Django 4.2.30 on 2026-06-01 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("crm", "0002_seed_system_tags_existing_orgs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0003_organization_plan_expires_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="LuckyDrawCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("ended", "Ended"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "daily_entry_limit_per_customer",
                    models.PositiveIntegerField(default=1),
                ),
                (
                    "total_entry_limit_per_customer",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("requires_name", models.BooleanField(default=True)),
                ("requires_phone", models.BooleanField(default=True)),
                ("requires_email", models.BooleanField(default=False)),
                ("consent_text", models.TextField()),
                ("privacy_notice_text", models.TextField(blank=True)),
                (
                    "default_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("zh-CN", "简体中文 (Simplified Chinese)"),
                            ("zh-TW", "繁體中文 (Traditional Chinese)"),
                        ],
                        default="zh-TW",
                        max_length=10,
                    ),
                ),
                ("deliver_coupon_via_whatsapp", models.BooleanField(default=True)),
                ("referral_enabled", models.BooleanField(default=True)),
                (
                    "referral_bonus_type",
                    models.CharField(
                        choices=[
                            ("extra_entry", "Extra Entry"),
                            ("better_odds", "Better Odds"),
                        ],
                        default="extra_entry",
                        max_length=12,
                    ),
                ),
                ("coupon_validity_days", models.PositiveIntegerField(default=14)),
                ("tag_redeemers_as_buffet", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lucky_draw_campaigns",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "lucky_draw_campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LuckyDrawPrize",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=100)),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("weight", models.PositiveIntegerField()),
                (
                    "max_wins_per_day",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("max_total_wins", models.PositiveIntegerField(blank=True, null=True)),
                ("wins_today_count", models.PositiveIntegerField(default=0)),
                ("wins_total_count", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prizes",
                        to="lucky_draw.luckydrawcampaign",
                    ),
                ),
            ],
            options={
                "db_table": "lucky_draw_prizes",
                "ordering": ["-weight", "-discount_percent"],
            },
        ),
        migrations.CreateModel(
            name="LuckyDrawEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_name", models.CharField(max_length=200)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("table_number", models.CharField(blank=True, max_length=20)),
                ("consent_given", models.BooleanField(default=False)),
                ("ip_address_hashed", models.CharField(blank=True, max_length=64)),
                ("user_agent_hash", models.CharField(blank=True, max_length=64)),
                (
                    "coupon_code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("drawn", "Drawn"),
                            ("redeemed", "Redeemed"),
                            ("expired", "Expired"),
                            ("invalid", "Invalid"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "referral_token",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                ("referral_count", models.PositiveIntegerField(default=0)),
                ("whatsapp_sent_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("entered_at", models.DateTimeField(auto_now_add=True)),
                ("drawn_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("redeemed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="lucky_draw.luckydrawcampaign",
                    ),
                ),
                (
                    "crm_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lucky_draw_entries",
                        to="crm.crmcustomer",
                    ),
                ),
                (
                    "prize",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="lucky_draw.luckydrawprize",
                    ),
                ),
                (
                    "redeemed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lucky_draw_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referred_by_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to="lucky_draw.luckydrawentry",
                    ),
                ),
            ],
            options={
                "db_table": "lucky_draw_entries",
                "ordering": ["-entered_at"],
            },
        ),
        migrations.CreateModel(
            name="LuckyDrawQRCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=100)),
                (
                    "qr_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="lucky_draw/qr/"
                    ),
                ),
                (
                    "poster_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="lucky_draw/posters/"
                    ),
                ),
                ("url_token", models.CharField(max_length=64, unique=True)),
                ("scan_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_codes",
                        to="lucky_draw.luckydrawcampaign",
                    ),
                ),
            ],
            options={
                "db_table": "lucky_draw_qr_codes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["url_token"], name="lucky_draw__url_tok_fef9f7_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="luckydrawprize",
            index=models.Index(
                fields=["campaign", "active"], name="lucky_draw__campaig_774af8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="luckydrawprize",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("discount_percent__gt", 0), ("discount_percent__lte", 100)
                ),
                name="lucky_draw_prize_discount_range",
            ),
        ),
        migrations.AddIndex(
            model_name="luckydrawentry",
            index=models.Index(
                fields=["campaign", "phone", "entered_at"],
                name="lucky_draw__campaig_50d110_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="luckydrawentry",
            index=models.Index(
                fields=["campaign", "ip_address_hashed", "entered_at"],
                name="lucky_draw__campaig_969388_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="luckydrawentry",
            index=models.Index(
                fields=["coupon_code"], name="lucky_draw__coupon__1dac86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="luckydrawentry",
            index=models.Index(
                fields=["referral_token"], name="lucky_draw__referra_142de7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="luckydrawentry",
            index=models.Index(
                fields=["campaign", "status"], name="lucky_draw__campaig_aa5708_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="luckydrawentry",
            index=models.Index(
                fields=["status", "expires_at"], name="lucky_draw__status_e4d730_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="luckydrawcampaign",
            index=models.Index(
                fields=["organization", "status"], name="lucky_draw__organiz_1f2efd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="luckydrawcampaign",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="lucky_draw__organiz_37178e_idx",
            ),
        ),
    ]
