# Generated by Django 4.2.30 on 2026-06-01 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0003_organization_plan_expires_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CRMCustomer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                ("phone_raw", models.CharField(blank=True, max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "whatsapp_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                (
                    "birthday_month",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("en", "English"),
                            ("zh-CN", "简体中文 (Simplified Chinese)"),
                            ("zh-TW", "繁體中文 (Traditional Chinese)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("booking", "Booking"),
                            ("chatbot", "Chatbot"),
                            ("whatsapp", "WhatsApp"),
                            ("instagram", "Instagram"),
                            ("messenger", "Messenger (not yet wired)"),
                            ("manual", "Manual"),
                            ("lucky_draw", "Lucky Draw"),
                            ("wifi", "WiFi"),
                            ("walk_in", "Walk-in"),
                            ("import", "Import"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("last_visit_date", models.DateField(blank=True, null=True)),
                ("last_interaction_at", models.DateTimeField(blank=True, null=True)),
                ("visit_count", models.PositiveIntegerField(default=0)),
                (
                    "marketing_consent_status",
                    models.CharField(
                        choices=[
                            ("not_asked", "Not Asked"),
                            ("given", "Given"),
                            ("refused", "Refused"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="not_asked",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_customers",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "crm_customers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CRMTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(default="#6366F1", max_length=7)),
                ("is_system", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_tags",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "crm_tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CRMSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("filter_rules", models.JSONField(default=dict)),
                ("customer_count", models.IntegerField(default=0)),
                ("is_dynamic", models.BooleanField(default=True)),
                ("last_evaluated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_segments",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "crm_segments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CRMInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("booking", "Booking"),
                            ("chatbot_message", "Chatbot Message"),
                            ("whatsapp_message", "WhatsApp Message"),
                            ("instagram_message", "Instagram Message"),
                            ("messenger_message", "Messenger Message (not yet wired)"),
                            ("phone_call", "Phone Call"),
                            ("walk_in", "Walk-in"),
                            ("lucky_draw_entry", "Lucky Draw Entry"),
                            ("wifi_signin", "WiFi Sign-in"),
                            ("manual_note", "Manual Note"),
                            ("coupon_redeemed", "Coupon Redeemed"),
                            ("whatsapp_coupon_sent", "WhatsApp Coupon Sent"),
                        ],
                        max_length=30,
                    ),
                ),
                ("source_channel", models.CharField(blank=True, max_length=20)),
                ("summary", models.TextField(blank=True, max_length=500)),
                ("related_entity_type", models.CharField(blank=True, max_length=50)),
                ("related_entity_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="crm.crmcustomer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_interactions",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "crm_interactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CRMCustomerTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_tags",
                        to="crm.crmcustomer",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_tags",
                        to="crm.crmtag",
                    ),
                ),
            ],
            options={
                "db_table": "crm_customer_tags",
            },
        ),
        migrations.CreateModel(
            name="CRMConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("consent_given", models.BooleanField()),
                (
                    "consent_source",
                    models.CharField(
                        choices=[
                            ("booking_form", "Booking Form"),
                            ("lucky_draw_form", "Lucky Draw Form"),
                            ("wifi_form", "WiFi Form"),
                            ("chatbot", "Chatbot"),
                            ("manual", "Manual"),
                            ("import", "Import"),
                        ],
                        max_length=20,
                    ),
                ),
                ("consent_text_snapshot", models.TextField()),
                ("consent_text_version", models.CharField(max_length=20)),
                (
                    "marketing_channels_allowed",
                    models.JSONField(blank=True, default=list),
                ),
                ("opt_out_timestamp", models.DateTimeField(blank=True, null=True)),
                ("privacy_notice_version", models.CharField(blank=True, max_length=20)),
                ("ip_address_hashed", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_records",
                        to="crm.crmcustomer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_consent_records",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "crm_consent_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="crmtag",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="uniq_crm_org_tag_name"
            ),
        ),
        migrations.AddIndex(
            model_name="crmsegment",
            index=models.Index(
                fields=["organization"], name="crm_segment_organiz_ece990_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crminteraction",
            index=models.Index(
                fields=["customer", "-created_at"],
                name="crm_interac_custome_de49a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="crmcustomertag",
            index=models.Index(
                fields=["tag", "customer"], name="crm_custome_tag_id_2b409c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="crmcustomertag",
            constraint=models.UniqueConstraint(
                fields=("customer", "tag"), name="uniq_crm_customer_tag"
            ),
        ),
        migrations.AddIndex(
            model_name="crmcustomer",
            index=models.Index(
                fields=["organization", "marketing_consent_status"],
                name="crm_custome_organiz_08b0fd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="crmcustomer",
            index=models.Index(
                fields=["organization", "source"], name="crm_custome_organiz_23d323_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crmcustomer",
            index=models.Index(
                fields=["organization", "birthday_month"],
                name="crm_custome_organiz_95bb37_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="crmcustomer",
            index=models.Index(
                fields=["organization", "last_visit_date"],
                name="crm_custome_organiz_16073e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="crmcustomer",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("phone__isnull", False), models.Q(("phone", ""), _negated=True)
                ),
                fields=("organization", "phone"),
                name="uniq_crm_org_phone",
            ),
        ),
        migrations.AddConstraint(
            model_name="crmcustomer",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("email__isnull", False), models.Q(("email", ""), _negated=True)
                ),
                fields=("organization", "email"),
                name="uniq_crm_org_email",
            ),
        ),
        migrations.AddIndex(
            model_name="crmconsent",
            index=models.Index(
                fields=["customer", "-created_at"],
                name="crm_consent_custome_cde4ae_idx",
            ),
        ),
    ]
