# Generated by Django 4.2.30 on 2026-06-03 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0003_organization_plan_expires_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditPack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "credits",
                    models.PositiveIntegerField(
                        help_text="Paid credits granted on purchase."
                    ),
                ),
                ("price_hkd", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="hkd", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "payments_credit_packs",
                "ordering": ["sort_order", "price_hkd"],
            },
        ),
        migrations.CreateModel(
            name="CreditPurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("credits", models.PositiveIntegerField()),
                ("amount_hkd", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="hkd", max_length=3)),
                (
                    "stripe_session_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("stripe_charge_id", models.CharField(blank=True, max_length=255)),
                ("stripe_receipt_url", models.URLField(blank=True)),
                ("credited", models.BooleanField(default=False)),
                ("usage_event_id", models.UUIDField(blank=True, null=True)),
                (
                    "refunded_amount_hkd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_purchases",
                        to="accounts.organization",
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="payments.creditpack",
                    ),
                ),
            ],
            options={
                "db_table": "payments_credit_purchases",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="payments_cr_organiz_9e8f42_idx",
                    ),
                    models.Index(
                        fields=["status"], name="payments_cr_status_cfe22a_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="creditpurchase",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stripe_payment_intent_id", ""), _negated=True),
                fields=("stripe_payment_intent_id",),
                name="uniq_payments_intent",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditpurchase",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stripe_session_id", ""), _negated=True),
                fields=("stripe_session_id",),
                name="uniq_payments_session",
            ),
        ),
    ]
