# Generated by Django 4.2.27 on 2025-12-27 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("handoff", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="handoffalert",
            new_name="handoff_ale_convers_b962ee_idx",
            old_name="handoff_ale_convers_8d5b02_idx",
        ),
        migrations.RenameIndex(
            model_name="handoffalert",
            new_name="handoff_ale_priorit_da97d1_idx",
            old_name="handoff_ale_priorit_9c2d3e_idx",
        ),
    ]
